# High resolution total alkalinity estimation using GLODAP2

In [22]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [25]:
import site
import pathlib

import numpy as np
import pandas as pd
import xarray as xr
from matplotlib import pyplot as plt
from scipy.special import huber
from sklearn import metrics

import highres_ta as ta

site.addsitedir("../scripts")
import train_quantile_ensemble as tqe

In [3]:
def scoring(y_true, y_pred) -> pd.DataFrame:
    from loguru import logger
    residuals = y_pred - y_true
    scores = pd.Series(
        {
            "root_mean_squared_error": metrics.root_mean_squared_error(y_true, y_pred),
            "mean_absolute_error": metrics.mean_absolute_error(y_true, y_pred),
            "huber_loss": huber(1.35, residuals).mean(),
            "median_absolute_error": metrics.median_absolute_error(y_true, y_pred),
            "mean_bias": residuals.mean(),
            "median_bias": residuals.median(),
            "r2_score": metrics.r2_score(y_true, y_pred),
        },
    name='Scores').to_frame()
    scores.index.name = "Metric"

    logger.info(f"\n{scores.to_markdown(floatfmt='.3f')}")

    return scores

# Training data

{'outer_splits': 6, 'inner_splits': 5, 'final_tuning_splits': 5}

In [32]:
config = tqe.load_config(pathlib.Path("../scripts/quantile_large_ensemble_config.yaml"))
data = tqe.prepare_data(config)

2026-09-18 13:01:01.844 | DEBUG    | highres_ta.dataio:load_data:18 - Loading 40 .pq files from /net/sea/work/gregorl/projects/highres_TA/data/training
2026-09-18 13:01:02.378 | DEBUG    | highres_ta.target_filtering:drop_bad_quality_talk:49 - TA values with large adjustments (<= 6.0 mol/kg): 2365
2026-09-18 13:01:02.380 | DEBUG    | highres_ta.target_filtering:drop_bad_quality_talk:52 - TA values without good flags (!= 2): 3046
2026-09-18 13:01:02.381 | INFO     | highres_ta.target_filtering:drop_bad_quality_talk:53 - Number of rows filtered due to large adjustments and bad flags: 5319 of 41534 (13%)
2026-09-18 13:01:02.458 | INFO     | train_quantile_ensemble:prepare_data:102 - Prepared 27,210 observations with 10 features


In [42]:
splits = ta.make_train_test_folds(
    data,
    n_splits=config["cross_validation"]["outer_splits"],
    shuffle=True,
    random_state=11,
)
splits

2026-09-18 14:23:05.944 | DEBUG    | highres_ta.train_test_split:make_salinity_bins:48 - Using the following bin edges for salinity: [20.1909  32.8038  34.05706 34.819   35.535   39.231  ]
2026-09-18 14:23:05.951 | DEBUG    | highres_ta.train_test_split:stratified_group_folds:96 - Making train-test splits stratified by salinity_bin and grouped by expocode


[(array([    0,     1,     6, ..., 27207, 27208, 27209], shape=(22674,)),
  array([    2,     3,     4, ..., 27191, 27192, 27193], shape=(4536,))),
 (array([    2,     3,     4, ..., 27207, 27208, 27209], shape=(22672,)),
  array([    0,     1,     6, ..., 26792, 26793, 26794], shape=(4538,))),
 (array([    0,     1,     2, ..., 27207, 27208, 27209], shape=(22677,)),
  array([   74,    75,    87, ..., 27132, 27133, 27134], shape=(4533,))),
 (array([    0,     1,     2, ..., 27207, 27208, 27209], shape=(22676,)),
  array([  463,   464,   465, ..., 26980, 26981, 26982], shape=(4534,))),
 (array([    0,     1,     2, ..., 27207, 27208, 27209], shape=(22674,)),
  array([   40,    45,    47, ..., 26873, 26874, 26875], shape=(4536,))),
 (array([    0,     1,     2, ..., 27191, 27192, 27193], shape=(22677,)),
  array([  948,   954,   955, ..., 27207, 27208, 27209], shape=(4533,)))]

# Model data

In [5]:
model = ta.QuantileRegressionEnsemble.load("../models/quantile_large_ensemble/models/quantile_ensemble.joblib")
model.optimise_cpus(max_cpus=84)
model.aggregation = "mean"

In [6]:
raw = ta.open_gridded_data()
x_names = tuple(model.estimators[0].feature_names)
features_ds = ta.open_inference_data(x_names)

In [7]:
yhat_ds = ta.predict_map_for_date(model, features_ds, date="2004-01-01")

In [20]:
ice = raw.seaice_fraction_cci.sel(time=yhat_ds.time.values).squeeze()
ice_mask = ice.fillna(0) < 0.15

q50 = yhat_ds.talk_pred.sel(quantile=0.5).squeeze().where(ice_mask)
dq80 = (
    yhat_ds.talk_pred
    .sel(quantile=[0.9, 0.1])
    .diff(dim="quantile")
    .squeeze()
    .where(ice_mask)
    .pipe(abs)
    .pipe(lambda x: x / 2.56)
    .clip(
        min=2.5,
    )
)
std = yhat_ds.talk_pred_q70.sel(quantile=0.5).squeeze().where(ice_mask)

custom = xr.concat([dq80, std], dim="a").mean(dim="a")
custom_max = custom.max()
custom_min = custom.min()
custom01 = custom.pipe(lambda x: (x - custom_min) / (custom_max - custom_min))
new_min = 2.5
custom = custom01.pipe(lambda x: x * (custom_max - new_min) + new_min)

In [ ]:
fig, axs = plt.subplots(2, 2, figsize=(12, 9), sharey=True, constrained_layout=True)
axs = axs.flatten()

props = {"robust": True, "cbar_kwargs": {"orientation": 'horizontal'}, "vmin": 1, "vmax": 25}
q50.plot.imshow(ax=axs[0], **(props | {"cmap": "RdYlBu_r", "vmin": 2200, "vmax": 2450}))
custom.plot.imshow(ax=axs[1], **props)
dq80.plot.imshow(ax=axs[2], **props)
std.plot.imshow(ax=axs[3], **props)

[ax.set_ylabel("") for ax in axs]
[ax.set_xlabel("") for ax in axs]
[ax.set_xticks([]) for ax in axs]
[ax.set_facecolor("k") for ax in axs]

In [19]:
std.compute().quantile([0.1, 0.2, 0.5])

<xarray.DataArray 'talk_pred_q70' (quantile: 3)> Size: 24B
array([ 4.54302025,  5.84535322, 10.27608395])
Coordinates:
  * quantile  (quantile) float64 24B 0.1 0.2 0.5